Metrics/AbcSize:
   Max: 20
   Exclude:
     - lib/jekyll/assets/env.rb
     - lib/jekyll/assets/plugins/html/pic.rb
     - lib/jekyll/assets/tag.rb
Metrics/BlockLength:
  Exclude:
    - jekyll-assets.gemspec
    - lib/jekyll/assets/plugins/magick.rb
    - lib/jekyll/assets/plugins/optim.rb
    - spec/tests/**/*
Metrics/BlockNesting: { Max: 4 }
Metrics/ClassLength: { Max: 480 }
Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - lib/jekyll/assets/env.rb
Metrics/LineLength: { Max: 112 }
Metrics/MethodLength: { Max: 32 }
Metrics/ModuleLength: { Max: 480 }
Metrics/ParameterLists: { Max: 6 }
Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - lib/jekyll/assets/env.rb

Layout/AlignArray:                     { Enabled: false }
Layout/AlignParameters:                { EnforcedStyle: with_fixed_indentation }
Layout/ClosingParenthesisIndentation:  { Enabled: false }
Layout/EmptyLineAfterMagicComment:     { Enabled: false }
Layout/EmptyLineBetweenDefs:           { AllowAdjacentOneLineDefs: true }
Layout/EmptyLinesAroundAccessModifier: { Enabled: false }
Layout/EmptyLinesAroundClassBody:      { Enabled: false }
Layout/EmptyLinesAroundModuleBody:     { Enabled: false }
Layout/ExtraSpacing:                   { AllowForAlignment: true }
Layout/FirstParameterIndentation:      { EnforcedStyle: consistent }
Layout/IndentArray:                    { EnforcedStyle: consistent }
Layout/IndentHash:                     { EnforcedStyle: consistent }
Layout/MultilineMethodCallIndentation: { EnforcedStyle: indented }
Layout/MultilineOperationIndentation:  { EnforcedStyle: indented }
Layout/SpaceAroundOperators:           { Enabled: false }
Layout/SpaceInsideBlockBraces:         { Enabled: false }
Layout/SpaceInsideBrackets:            { Enabled: false }
Layout/SpaceInsideHashLiteralBraces:   { Enabled: false }
Layout/SpaceInsideStringInterpolation: { Enabled: false }

Lint/IneffectiveAccessModifier:
  Exclude:
    - lib/jekyll/assets/hook.rb
    - lib/jekyll/assets/config.rb
Lint/UnusedMethodArgument:
  Exclude:
    - lib/jekyll/assets/extensible.rb
Lint/UselessAssignment:
  Exclude:
    - lib/jekyll/assets/env.rb
    - lib/jekyll/assets/plugins/magick.rb
Lint/UselessAccessModifier:            { Enabled: false }

Naming/FileName:                       { Enabled: false }

Performance/HashEachMethods:
  Exclude:
    - spec/tests/lib/jekyll/assets/env_spec.rb
    - lib/jekyll/assets/plugins/liquid.rb

Style/BracesAroundHashParameters:      { Enabled: false }
Style/Documentation:                   { Enabled: false }
Style/DoubleNegation:                  { Enabled: false }
Style/GuardClause:                     { Enabled: false }
Style/HashSyntax:                      { Enabled: false }
Style/IfUnlessModifier:                { Enabled: false }
Style/IfWithSemicolon:
  Exclude:
    - lib/jekyll/assets/plugins/html/pic.rb
Style/ModuleFunction:                  { Enabled: false }
Style/MultilineTernaryOperator:        { Enabled: false }
Style/MutableConstant:                 { Enabled: false }
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'
    '%r': '!!'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'
Style/RedundantReturn:                 { Enabled: false }
Style/RegexpLiteral:                   { Enabled: false }
Style/RescueModifier:                  { Enabled: false }
Style/Semicolon:                       { AllowAsExpressionSeparator: true }
Style/SignalException:                 { EnforcedStyle: only_raise }
Style/StringLiterals:                  { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation:   { EnforcedStyle: double_quotes }
Style/UnneededCapitalW:                { Enabled: false }

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - examples/**/*
    - vendor/**/*
