#!/bin/bash
[ "$DEBUG" = "true" ] && set -x
VERBOSE=${VERBOSE:-false}
set -e

# --
copyMsg() {
  if [ "$VERBOSE" = "true" ]; then
    printf "📄 $1\n"
  fi
}

# --
warnMsg() {
  if [ "$VERBOSE" = "true" ]; then
    printf "⚠️  $1\n"
  fi
}

# --
doneMsg() {
  if [ "$VERBOSE" = "true" ]; then
    printf "💖 $1\n"
  fi
}

skip_if_exists=(Gemfile)
skip_if_external=(CONTRIBUTING.md CODE_OF_CONDUCT.md)
gurl=https://github.com/envygeeks
cdir=$PWD

# --
# Copies everything, except for what's to be skipped if
#   it happens to exist, into the current directory, so that
#   stays in sync with the parent.
# --
for g in "ruby-dev" "github-dev"; do
  dir=$(mktemp -d)
  git clone $gurl/$g.git $dir >/dev/null 2>&1
  warnMsg "Cloned $gurl/$g.git"
  cd $dir
  
  for f in $(ls -a | grep -vE '^(\.{1,2}|\.git)$'); do
    skip=false

    # --
    # Files we do not wish to copy if they already exist.
    #   There is no reason to overwrite, or they will
    #   generally just conflict.
    # --
    for s in "${skip_if_exists[@]}"; do
      if [ "$f" = "$s" ] && [ -f "$cdir/$f" ]; then
        skip=true
      fi
    done
    
    # --
    # Files that shouldn't be copied if I'm not the lead
    #   maintainer.  They might have their own stuff.
    # --
    if [ -f ".external" ]; then
      for s in "${skip_if_external}"; do
        if [ "$f" = "$s" ] && [ -f "$cdir/$f" ]; then
          skip=true
        fi
      done
    fi

    # --
    if [ "$skip" = "true" ]; then
      continue
    else
      copyMsg "Copying $f into ."
      cp -r $f $cdir
    fi
  done
  
  cd $cdir
  doneMsg "Done!"
  rm -rf $dir
done